// Random book data that is added to Firestore
// After you've signed into Book Reviews, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  bookTitles: [
    "The Enchanted Quest",
    "Mysteries of the Deep",
    "Whispers in the Wind",
    "Chronicles of Tomorrow",
    "The Lost Kingdom",
    "Echoes of the Past",
    "Shadows and Light",
    "The Last Stand",
    "Journey to Eternity",
    "Breaking Barriers",
    "The Hidden Truth",
    "Dreams and Reality",
    "The Final Chapter",
    "Beyond Horizons",
    "The Secret Keeper",
    "Winds of Change",
    "The Forgotten Promise",
    "Eternal Flame",
    "The Silent Warrior",
    "Crossroads of Fate",
    "The Untold Story",
    "Paths of Destiny",
    "The Unseen World",
    "Legends Reborn",
    "The Broken Mirror",
    "Tales from Afar",
    "The Chosen One",
    "Secrets Unveiled",
    "The Midnight Hour",
    "Starlight Chronicles",
    "The Guardian's Call",
    "Time's Arrow",
    "The Ancient Prophecy",
    "Waves of Destiny",
    "The Hidden Path",
    "Echoes of Silence",
    "The Crimson Tide",
    "Beyond the Veil",
    "The Last Light",
    "The Wanderer's Tale",
    "Sands of Time",
    "The Broken Crown",
    "The Eternal Quest",
    "Whispers of the Heart",
    "The Final Countdown",
  ],
  bookAuthors: [
    "Sarah Mitchell",
    "James Chen",
    "Emily Rodriguez",
    "Michael Thompson",
    "Rachel Anderson",
    "David Kim",
    "Lisa Park",
    "Christopher Brown",
    "Jessica Taylor",
    "Daniel Wilson",
    "Amanda Lee",
    "Robert Martinez",
    "Jennifer White",
    "Matthew Harris",
    "Nicole Garcia",
    "Andrew Davis",
    "Michelle Clark",
    "Kevin Lewis",
    "Stephanie Walker",
    "Ryan Hall",
    "Lauren Allen",
    "Brian Young",
    "Ashley King",
    "Jonathan Wright",
    "Olivia Scott",
    "Tyler Green",
    "Megan Adams",
    "Nathan Baker",
    "Brittany Nelson",
    "Joshua Hill",
  ],
  publicationYears: [
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025",
  ],
  bookGenres: [
    "Fiction",
    "Non-Fiction",
    "Mystery",
    "Romance",
    "Science Fiction",
    "Fantasy",
    "Biography",
    "History",
    "Self-Help",
    "Thriller",
  ],
  bookReviews: [
    { text: "An absolutely captivating read! I couldn't put it down.", rating: 5 },
    { text: "Beautifully written with rich characters and compelling plot.", rating: 5 },
    { text: "The author's prose is exquisite and the story is engaging.", rating: 5 },
    { text: "A masterpiece of storytelling that touched my heart.", rating: 5 },
    { text: "One of the best books I've read this year!", rating: 5 },
    {
      text: "The narrative flow is perfect and the ending is satisfying.",
      rating: 5,
    },
    { text: "Well-crafted characters that feel real and relatable.", rating: 5 },
    { text: "The world-building is immersive and well-thought-out.", rating: 5 },
    { text: "Enjoyable read with good pacing and interesting themes.", rating: 4 },
    { text: "Solid story, would recommend to others.", rating: 4 },
    { text: "Well-written with interesting plot twists.", rating: 4 },
    { text: "Good characters, but some parts felt rushed.", rating: 3 },
    { text: "Decent read, but nothing particularly memorable.", rating: 3 },
    { text: "The plot was okay, but the writing style didn't suit me.", rating: 3 },
    {
      text: "The pacing was off and the characters felt underdeveloped.",
      rating: 2,
    },
    { text: "Disappointing execution of an interesting premise.", rating: 2 },
    { text: "The story had potential but fell flat.", rating: 2 },
    { text: "Found it hard to stay engaged throughout.", rating: 2 },
    {
      text: "The writing was poor and the plot was confusing.",
      rating: 1,
    },
    {
      text: "Worst book I've read in a long time, couldn't finish it.",
      rating: 1,
    },
    { text: "Terrible writing, no character development, plot holes everywhere.", rating: 1 },
    { text: "Complete waste of time, very disappointed.", rating: 1 },
    { text: "Absolutely brilliant! A must-read for everyone.", rating: 5 },
    { text: "The emotional depth in this book is remarkable.", rating: 5 },
    { text: "Top-notch quality, highly recommend!", rating: 5 },
    { text: "Perfect for book club discussions.", rating: 5 },
    { text: "The author's best work yet, truly exceptional.", rating: 5 },
    { text: "A gem of a book, beautifully crafted in every way.", rating: 5 },
    { text: "Excellent selection of themes and writing style.", rating: 5 },
    { text: "A fantastic literary experience overall.", rating: 5 },
    {
      text: "The characters were well-developed, though the plot was a bit slow.",
      rating: 4,
    },
    { text: "Good read, but the ending left me wanting more.", rating: 4 },
    {
      text: "Enjoyed it, especially the middle sections.",
      rating: 4,
    },
    { text: "Well-structured narrative and engaging dialogue.", rating: 4 },
    { text: "Satisfying read for a lazy weekend.", rating: 4 },
    { text: "The book was okay, nothing special though.", rating: 3 },
    {
      text: "Some interesting ideas, but execution was mediocre.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more depth and complexity.", rating: 2 },
    { text: "The writing style was uninspiring.", rating: 2 },
    {
      text: "Regret spending time on such a disappointing book.",
      rating: 2,
    },
    { text: "Not up to par with other books in this genre.", rating: 2 },
  ],
};
